### ISSUE TITLE
fix: layout Header and footer

### ISSUE THREAD

**Issue by thangduongnfq** [U2Fly-NFQ/Frontend#33]
i just test at mobile M pls check this
![image](https://user-images.githubusercontent.com/104955889/176985206-a0acc10c-7d26-4449-bf75-d18408afe716.png)
![image](https://user-images.githubusercontent.com/104955889/176985210-6a329f36-4e9f-4611-94dc-c235a6201816.png)

**Comment by DucTranNFQ** [comment]
Ok, I will fix them.
